### ISSUE TITLE
Feature request: smarter label size logic

### ISSUE THREAD

**Issue by davemcg** [rlbarter/superheat#10]
I'm finding it incredibly fiddly to get the bottom and left text displayed in the boxes without too much or too little text visible. It would be great if some kind of logic to roughly match box size to max(text length).

**Comment by rlbarter** [comment]
Will roll this out soon!

**Comment by rlbarter** [comment]
Ok I've edited development version of the package that *should* automatically make the label size a bit smarter based on the length of the text labels. 

I haven't tested it as thoroughly as I could have so if you get a chance to try it out and find that it's behaving weirdly, please let me know!
