### ISSUE TITLE
feature request:max value option?

### ISSUE THREAD

**Issue by davemcg** [rlbarter/superheat#12]
I don't think this is possible....could you add a to make the the Z values higher or lower than a cutoff to be the lowest or highest color? Right now they go to gray, which isn't the behavior I want.

Something like how plot_ly has zmax: 
http://stackoverflow.com/questions/39674378/fix-plotly-color-scale-breaks

**Comment by rlbarter** [comment]
Good suggestion! It is not possible right now, but I will add this to my to-do list and implement it when I get a chance.

**Comment by rlbarter** [comment]
I just added an argument called `extreme.values.na` so that setting `extreme.values.na = FALSE` sets all values outside the range specified by `heat.lim` to the limit value. For example, try
```
superheat(matrix(c(1, 2, 5, 8, 9, 3), ncol = 2), 
                  heat.lim = c(1, 7), 
                  extreme.values.na = FALSE)
```
compared with setting `extreme.values.na = TRUE`. 

Does this provide the behaviour you were seeking?
