### ISSUE TITLE
barplot: ylim option in 'yt' or xlim option in 'yr' 

### ISSUE THREAD

**Issue by grepinsight** [rlbarter/superheat#13]
Hi,

Thank you for making this package! It's a breath of fresh air to create heatmaps with this package.

The issue I have is when I try to create three separate heatmaps with additional bar plots in "yt" in each heatmap, the barplot's ylim are inconsistent across the plots, as you can see below.

![](http://i.imgur.com/Vx8vFiX.png)

Is there anyway to provide a fixed ylim values for 'yt' for 'yr'?

**Comment by rlbarter** [comment]
Hi!

**Comment by rlbarter** [comment]
Ignore my accidental closing! 

I'll implement this ASAP. It was one of those things that I assumed you could already do, but I never actually implemented it! Well let you know when I have done so.

**Comment by rlbarter** [comment]
I've added arguments `yt.lim` and `yr.lim` which take a vector of length 2, where the first entry is the minimum value for the range and the second entry is the maximum value for the range. 
See the updated vignette: https://rlbarter.github.io/superheat/adjacent-plots.html#limits
Let me know if you run into any issues!

**Comment by rlbarter** [comment]
You will need to re-install the development version

`devtools::install_github("rlbarter/superheat")`

**Comment by grepinsight** [comment]
@rlbarter Thank you so much for the quick response!! superheat is really powerful.

**Comment by rlbarter** [comment]
No problem - I'm glad it's useful!
