### ISSUE TITLE
Running into issues when trying to use Superheat

### ISSUE THREAD

**Issue by Gr33nM0nk** [rlbarter/superheat#15]
My code goes as follows:

`library(superheat)`
`superheat(data, row.dendrogram = T, col.dendrogram = T)`
But unfortunately, I keep receiving the folowing error:
`Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘DBI’ `

I've tried to install superheat along with its dependencies but it does not seem to work.
Any ideas?

**Comment by rlbarter** [comment]
Hi Chen,

A few questions to help figure out the problem:

Are you getting this error when you install superheat (`install.packages("superheat")` or `devtools::install_github("rlbarter/superheat")`), when you load superheat (`library(superheat)`), or when you try to use the superheat function?

Can you please also provide the output of `sessionInfo()`?

**Comment by Gr33nM0nk** [comment]
Hey there!

I am getting the error that's mentioned above when trying to user the superheat function.
Installing the package and loading it works fine.

Here's the output of sessionInfo() for your convenience:
`R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] plyr_1.8.4      superheat_0.1.0 gplots_3.0.1    ggplot2_2.2.0  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8        gtools_3.5.0       assertthat_0.1     MASS_7.3-45        bitops_1.0-6      
 [6] grid_3.3.3         gtable_0.2.0       magrittr_1.5       scales_0.4.1       KernSmooth_2.23-15
[11] lazyeval_0.2.0     gdata_2.17.0       ggdendro_0.1-20    tools_3.3.3        munsell_0.4.3     
[16] colorspace_1.3-1   caTools_1.17.1     tibble_1.2      `

Hope that will assist you in the realization of the error here.
Thanks!

**Comment by rlbarter** [comment]
That is very odd... I've seen that kind of error before when trying to *install* the package, but not when trying to use a function.

I have a few suggestions:

First restart a clean R session, then 
- try installing from github: `devtools::install_github("rlbarter/superheat")`
- if that doesn't work, try manually installing the dependencies: `install.packages("DBI")`.

I've also heard of antivirus software on Windows causing problem with write problems... Perhaps temporarily shutting that off might do the trick?

Let me know how that goes!

**Comment by Gr33nM0nk** [comment]
Executing install.packages("DBI") actually solved the problem!
Thank you @rlbarter :)

**Comment by rlbarter** [comment]
Yay! It's always tough to figure out what's going on with someone else's system, but I'm glad that we got to the bottom of it :).
