### ISSUE TITLE
heat.lim / heat.na.col

### ISSUE THREAD

**Issue by alextamburino** [rlbarter/superheat#2]
Hi,

I just started using superheat and I like it a lot. 

The only issue I'm having is related to the colors. I have data that is positive and negative. The distribution is is right skewed (e.g. 800 postive values, max 7 & 400 negative values, min -4), but I need the color scheme to be normally distributed around zero (e.g. green for positive values and red for negative).

What's the easiest way to do this?

Alex

superheat(x,
          pretty.order.rows = TRUE, pretty.order.cols = TRUE,
          heat.pal = redgreen(100),heat.na.col = "gray15",
          legend.height = 0.2, legend.width = 2, legend.text.size = 20)

![image](https://cloud.githubusercontent.com/assets/25646506/22755189/0f896d68-ee10-11e6-963a-814c0a5349fe.png)

**Comment by rlbarter** [comment]
You can use the `heat.pal.values` argument to specify where the color transitions happen. See the color transition section of the vignette: https://rlbarter.github.io/superheat/heatmap-colormap.html#color-transitions

Let me know if you need more details on this!

**Comment by rlbarter** [comment]
Closing since there has been no further questions.

**Comment by alextamburino** [comment]
Great. Thanks!
