### ISSUE TITLE
Add options to control size of names of columns and rows of the heatmap

### ISSUE THREAD

**Issue by LucasMS** [rlbarter/superheat#20]
With longer names on the columns and rows in the heatmap, I observed that the names were badly positioned, hidden behind the heatmap. Could not find a way to adjust this.

Thanks for the good work :)

**Comment by rlbarter** [comment]
This should be possible using the `left.label.text.size` and `.bottom.label.text.size` arguments. See the vignette section on this: https://rlbarter.github.io/superheat/labels.html#label-text-size.

**Comment by LucasMS** [comment]
Thanks :)
