### ISSUE TITLE
Change position of label and additional plots

### ISSUE THREAD

**Issue by LoreenMamerow** [rlbarter/superheat#22]
Hi there, great package, very useful! 

One brief question: Is it possible to have the bottom label be displayed above the heat map and the current yt-graph underneath the heat map? Basically, is it possible to change the location of column labels and additional plots?

Apologies if this is a trivial question, I have been trying to change the plotting options but so far have not been successful. 

Thank and best, Loreen

**Comment by rlbarter** [comment]
Hi Loreen,

Unfortunately at the moment it is not possible to display the yt graph below the heatmap and the labels above the heatmap. I'm hoping to at some point implement this, but haven't yet had the chance to work on it. I'll leave this issue open so that I can close it when I eventually get around to it!

Sorry about that!

**Comment by LoreenMamerow** [comment]
Hi Rebecca,

Thanks a lot for your response, that is good to know!

On a related note, I have been trying to plot multiple correlations in yt (same columns, just different variable) within the superheat function, but have not quite managed it yet. Is there a simple way of adding points to the yt graph (essentially like using 'plot' in R followed by 'points')? Of course I could achieve this easily as a separate graph and then put this together with the heat map, but the layout works quite nicely with superheat, so any advice on whether an additional plot showing multiple correlations can be achieved would be great.

Thanks again for developing the package, so far it has been really useful!

Best, Loreen

**Comment by rlbarter** [comment]
Hi Loreen, unfortunately it also isn't possible to plot multiple variables in yt yet. This is pretty high on my to-do list though so keep an eye on it. I'll update the CRAN version when I eventually get around to adding this feature (as well as a feature for multiple labels).
