### ISSUE TITLE
Svg output

### ISSUE THREAD

**Issue by brandries** [rlbarter/superheat#28]
Hi rlbarter

Thanks for a great package, one of the greatest heatmaps I've seen so far.

When I output to svg or pdf, the heatmap produce an almost smudged effect, see below. 
Has anyone else encountered this issue?

Thanks
![heatmap_smudge](https://user-images.githubusercontent.com/13015962/30913030-05c5ff6e-a38f-11e7-9022-0195d02dfd3c.png)

**Comment by rlbarter** [comment]
In my experience, this depends on the viewer you use. For example, on a mac, if I use preview (the default viewer), I sometimes see this smudgy effect, but if I use Adobe Acrobat, it is clear (I suspect that Adobe Acrobat uses a higher resolution to view pdfs than preview... or something like that).

Can you let me know if you experience the same thing when using a different viewer? If so, then we will have to dig a bit deeper!

**Comment by brandries** [comment]
Thanks for the speedy reply!
I found the same thing, adobe seems to work fine opposed to my editor which did the smudgy effect.
If I run into issues again I will contact you. Thanks
