### ISSUE TITLE
Linux hangup on install

### ISSUE THREAD

**Issue by cranknasty** [rlbarter/superheat#33]
Hiya, each time I attempt to install on my linux box (Rstudio server) it stalls indefinitely any ideas?.
`> R.version
               _                           
platform       x86_64-redhat-linux-gnu     
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          4.3                         
year           2017                        
month          11                          
day            30                          
svn rev        73796                       
language       R                           
version.string R version 3.4.3 (2017-11-30)
nickname       Kite-Eating Tree`

**Comment by rlbarter** [comment]
Hmm I honestly have no idea on this one! 

What code did you run to produce this output?

**Comment by cranknasty** [comment]
I ended up fixing it in a roundabout way. I think my memory buffer was too
full and the package wasnt fully loading. But now clean restarted and it
works.
