### ISSUE TITLE
legend.breaks ?

### ISSUE THREAD

**Issue by EastBayEv** [rlbarter/superheat#35]
Hi - I am trying to run the first example here: https://rlbarter.github.io/superheat/legend.html#legend-breaks

The code looks like this: 
```
superheat(mtcars,
          # scale the matrix columns
          scale = TRUE,
          
          # specify the legend breaks
          legend.breaks = c(-0.5, 0.5, 1.5))
```

However, this produces the error message: 

```
Error in superheat(mtcars, scale = TRUE, legend.breaks = c(-0.5, 0.5,  : 
  unused argument (legend.breaks = c(-0.5, 0.5, 1.5))
```

I could simply be missing something, but I thought I would ask because `legend.breaks` does not appear in the ?superheat help list of arguments. 

Thanks!

**Comment by rlbarter** [comment]
Hi Evan,
I suspect the issue is that you're using the CRAN version of the package, but a lot of the documentation is for the dev version on github. (The CRAN version will be updated soon).

Try installing from github

```
install.packages("devtools")
devtools::install_github("rlbarter/superheat")
library(superheat)
```
and let me know if this fixes the problem.
