### ISSUE TITLE
Spread out legend tick marks?

### ISSUE THREAD

**Issue by ryjohnson09** [rlbarter/superheat#4]
Hi Rebecca, 

Loving superheat! One questions about the legend tick marks. Is there anyway to specify the values of the tick marks? For example, in the heatmap below, two of my tick marks are very close together causing the values to overlap. How do I spread out the tick marks?

Thanks,
Ryan

![rplot](https://cloud.githubusercontent.com/assets/10009758/22895674/5f7ddb54-f1eb-11e6-8460-7ec2580f3936.png)

```
superheat(as.matrix(dat), left.label.size = 0.4, left.label.text.size = 4, bottom.label.size=0.5, bottom.label.text.size = 4, bottom.label.text.angle = 90, pretty.order.cols = TRUE, pretty.order.rows = TRUE, yt=snps, yt.axis.name = "\n\n\n# of SNPs", yt.plot.type="bar", row.dendrogram = TRUE, yt.axis.name.angle = 90, legend.width = 3, yt.axis.name.size = 12)
```

**Comment by rlbarter** [comment]
Hi Ryan,

I have just added a feature allowing the user to specify the legend break positions.

You will need to re-install the development version of superheat and then you can evoke the `legend.breaks` argument. See the entry in the vignette: https://rlbarter.github.io/superheat/legend.html#legend-breaks

I hope that helps!
Rebecca

**Comment by ryjohnson09** [comment]
Worked perfectly...thanks for your help!

Ryan

**Comment by nkanrar** [comment]
Hi Rebecca,

Thanks for this great tool! I'm trying to specify the breaks of my colorbar right now and my system doesn't identify `legend.breaks` as a valid argument to the `superheat` function at the moment. I installed from the GitHub repo as suggested above. Not sure if perhaps I'm making a mistake?

Thanks,

Niv
