### ISSUE TITLE
Integration with seriation

### ISSUE THREAD

**Issue by axitamm** [rlbarter/superheat#45]
Hi Rebecca,

Excellent package! Super easy to use! Great features and graphics output options! Minor question: Can seriation package functions (https://cran.r-project.org/web/packages/seriation/index.html) be integrated into superheat?

Again, great package!

**Comment by rlbarter** [comment]
Hi there axitamm,
Unfortunately I'm not familiar with seriation objects, having never used that package myself. If they can be converted easily into matrices then integration would be straightforward (and perhaps should be done by the user than the package itself). Unfortunately I don't really have the time to implement much beyond simple edits and bug fixes at the moment.
