### ISSUE TITLE
Smeared pdf output using RStudio

### ISSUE THREAD

**Issue by HaoZhang17** [rlbarter/superheat#47]
Hi Rebecca,

Thanks for your nice tool! I found the plot would be smeared when using the "export pdf" function in RStudio, could you please figure out the reason? Thanks!

Best,
Hao

![image](https://user-images.githubusercontent.com/30916517/48049298-233aa980-e1d9-11e8-995b-1257816aa3d1.png)

**Comment by rlbarter** [comment]
Hi Hao,

I am aware of this problem and have been unable to figure out what causes it. Exporting to png ("Save as image") rather than pdf seems to fix it.
