### ISSUE TITLE
Fr: option to combine plots / export plot object

### ISSUE THREAD

**Issue by vpeddu** [rlbarter/superheat#51]
Hi, I'm using superheat to generate figures for a publication- its fantastic! However, I would like to combine two figures into a panel. It would be wonderful if there were a way to position two superheat plots next to each other such as cowplot does with ggplot graphs.

Thanks!

**Comment by rlbarter** [comment]
Unfortunately I'm not aware of a way to do this and sadly I'm not actively working on the package at the moment. If you find a solution though, I'd be very interested to see it!
