### ISSUE TITLE
feature request: heatmap body to be dotplot

### ISSUE THREAD

**Issue by crazyhottommy** [rlbarter/superheat#52]
Hi Rebecca,
Many thanks for this package in the ggplot2 space. I like it very much. Do you think you can add support for a figure like below:
![image](https://user-images.githubusercontent.com/4106146/77327662-eef25b00-6cf1-11ea-8fa6-e39fd901e793.png)

The current solution is https://davemcg.github.io/post/lets-plot-scrna-dotplots/ 
I think it would be great for you to add this feature, as it is very useful for scRNAseq analysis.

Best,
Tommy

**Comment by rlbarter** [comment]
Hi Tommy,

I'm glad you're finding superheat useful! Unfortunately I'm not actively working on superheat at the moment (and probably won't be for the foreseeable future). I'll let you know if that changes in the future though!

Rebecca

**Comment by crazyhottommy** [comment]
Thanks!
