### ISSUE TITLE
Plotting more than one value on adjacent scatter plot

### ISSUE THREAD

**Issue by vpeddu** [rlbarter/superheat#54]
This package generates beautiful plots thank you so much for creating this! I'm attempting to plot two values per column on a YT scatter plot grouped by color. I can get one or the other to plot, but i can't seem to combine them to plot two values per column on YT at the same time. Is there a solution for this?

**Comment by rlbarter** [comment]
Hi!

Unfortunately this feature of plotting two values per row/column doesn't exist, and I'm not actively working on superheat these days, so unless someone else does it, it's not likely to be implemented any time soon.

Sorry about that!

Rebecca
