### ISSUE TITLE
Can rectangles or colors be added to the dendrogram? 

### ISSUE THREAD

**Issue by gtalckmin** [rlbarter/superheat#55]
Hello Rebecca,

Great package. I went through the documentation and I could not find information on how to add extra-features to the dendrogram. I would be keen to color or add an dashed rectangles over a group of braches.

I noticed that the ggdendro is used and I assume a ggdendro object is displayed as a grob. However, I am usure how to extract, modify it and inject it back to the superheat object.

Great package anyhow! 
Cheers

**Comment by gtalckmin** [comment]
I added a larger description on stackoverflow:
https://stackoverflow.com/questions/63169640/r-package-superheat-adding-color-or-rectangles-to-the-dendrograms

**Comment by rlbarter** [comment]
Hello!

Unfortunately I don't think this is possible right now, but it shouldn't be too hard to implement if you wanted to do it since you already found the part where ggdendro is used!

Sadly, I don't really have the bandwidth to make active changes to superheat and test them right now :(
