### ISSUE TITLE
Displaying more than 100 row names

### ISSUE THREAD

**Issue by davemcg** [rlbarter/superheat#8]
I can't get superheat to show more than 100 row names. I'm trying to make a REALLY tall plot and I need the left (row) labels to be printed. Is there an option somewhere I'm missing?

**Comment by rlbarter** [comment]
Yes there is an argument `force.left.label` that you can set to `TRUE` :).

**Comment by davemcg** [comment]
Oh, great. There are so many ways to customize superheat I couldn't find it. I was searching for everything left.*
